name: assignment
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Network
  http: ^0.13.4
  json_annotation: ^4.4.0

  # State Management
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  # Utils
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
